version: '3'
services:
  core:
    build: .
    ports:
     - "3000:3000"
    links:
    - "hacker-news-client:hacker-news"
  hacker-news-client:
    build: ../hacker-news-client
    ports:
    - "4000:4000"
