version: '3'
services:
  front-end:
    build: ../front-end
    ports:
     - "8080:8080"
  core:
    build: .
    ports:
     - "3000:3000"
  hacker-news-client:
    build: ../hacker-news-client
    ports:
    - "4000:4000"
  facebook-client:
    build: ../facebook-client
    ports:
    - "5000:5000"
  reddit-client:
    build: ../reddit-client
    ports:
    - "3001:3001"
  google-news-client:
    build: ../google-news-client
    ports:
    - "7000:7000"
    env_file:
    - ../google-news-client/workspace.env
