version: '3'
services:
  front-end:
    build: ../front-end
    ports:
     - "443:443"
    volumes:
     - /usr/local/etc/ssl/certs/frontend.crt:/usr/local/etc/ssl/certs/frontend.crt
     - /usr/local/etc/ssl/private/frontend.key:/usr/local/etc/ssl/private/frontend.key
  core:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - /usr/local/etc/ssl/certs/reddit.crt:/usr/local/etc/ssl/certs/reddit.crt
     - /usr/local/etc/ssl/certs/core.crt:/usr/local/etc/ssl/certs/core.crt
     - /usr/local/etc/ssl/private/core.key:/usr/local/etc/ssl/private/core.key
  hacker-news-client:
    build: ../hacker-news-client
    ports:
    - "4000:4000"
  facebook-client:
    build: ../facebook-client
    ports:
    - "5000:5000"
  reddit-client:
    build: ../reddit-client
    ports:
    - "3001:3001"
    volumes:
     - /usr/local/etc/ssl/certs/core.crt:/usr/local/etc/ssl/certs/core.crt
     - /usr/local/etc/ssl/certs/reddit.crt:/usr/local/etc/ssl/certs/reddit.crt
     - /usr/local/etc/ssl/private/reddit.key:/usr/local/etc/ssl/private/reddit.key
  google-news-client:
    build: ../google-news-client
    ports:
    - "7000:7000"
    env_file:
    - ../google-news-client/workspace.env
  rss-client:
    build: ../rss-client
    ports:
    - "9000:9000"
