version: '3'
services:
  front-end:
    image: icedmocha/front-end
    ports:
     - "443:443"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
     - /home/docker/ssl/certs/frontend.crt:/usr/local/etc/ssl/certs/frontend.crt
     - /home/docker/ssl/private/frontend.key:/usr/local/etc/ssl/private/frontend.key
    logging:
      driver: json-file
  core:
    image: icedmocha/core
    ports:
     - "3000:3000"
    env_file:
    - workspace.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
     - /home/docker/ssl/certs/reddit.crt:/usr/local/etc/ssl/certs/reddit.crt
     - /home/docker/ssl/certs/core.crt:/usr/local/etc/ssl/certs/core.crt
     - /home/docker/ssl/private/core.key:/usr/local/etc/ssl/private/core.key
    logging:
      driver: json-file
  hacker-news-client:
    image: icedmocha/hacker-news-client
    ports:
    - "4000:4000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: json-file
  facebook-client:
    image: icedmocha/facebook-client
    ports:
    - "5000:5000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: json-file
  reddit-client:
    image: icedmocha/reddit-client
    ports:
    - "3001:3001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
     - /home/docker/ssl/certs/core.crt:/usr/local/etc/ssl/certs/core.crt
     - /home/docker/ssl/certs/reddit.crt:/usr/local/etc/ssl/certs/reddit.crt
     - /home/docker/ssl/private/reddit.key:/usr/local/etc/ssl/private/reddit.key
    logging:
      driver: json-file
  google-news-client:
    image: icedmocha/google-news-client
    ports:
    - "7000:7000"
    env_file:
    - ../google-news-client/workspace.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: json-file
