version: '3'
services:
  front-end:
    image: icedmocha/front-end
    ports:
     - "443:443"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
     - /etc/ssl/certs/frontend.crt:/etc/ssl/certs/frontend.crt
     - /etc/ssl/private/frontend.key:/etc/ssl/private/frontend.key
  core:
    image: icedmocha/core
    ports:
     - "3000:3000"
    env_file:
    - workspace.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
     - /etc/ssl/certs/core.crt:/etc/ssl/certs/core.crt
     - /etc/ssl/private/core.key:/etc/ssl/private/core.key
  hacker-news-client:
    image: icedmocha/hacker-news-client
    ports:
    - "4000:4000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  facebook-client:
    image: icedmocha/facebook-client
    ports:
    - "5000:5000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  reddit-client:
    image: icedmocha/reddit-client
    ports:
    - "3001:3001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
     - /etc/ssl/certs/reddit.crt:/etc/ssl/certs/reddit.crt
     - /etc/ssl/private/reddit.key:/etc/ssl/private/reddit.key
  google-news-client:
    image: icedmocha/google-news-client
    ports:
    - "7000:7000"
    env_file:
    - ../google-news-client/workspace.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
